/// Flutter icons CurvedIcon2
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CurvedIcon2
///      fonts:
///       - asset: fonts/CurvedIcon2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CurvedIcon2 {
  CurvedIcon2._();

  static const _kFontFam = 'CurvedIcon2';
  static const String? _kFontPkg = null;

  static const IconData wallet = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
