/// Flutter icons CurvedIcon4
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CurvedIcon4
///      fonts:
///       - asset: fonts/CurvedIcon4.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CurvedIcon4 {
  CurvedIcon4._();

  static const _kFontFam = 'CurvedIcon4';
  static const String? _kFontPkg = null;

  static const IconData checkbox_marked_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
